# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_ref', models.CharField(max_length=50)),
                ('rloiid', models.IntegerField()),
                ('url', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=100)),
                ('river_name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('stage_scale_url', models.CharField(max_length=150)),
                ('typical_low', models.FloatField()),
                ('typical_high', models.FloatField()),
            ],
        ),
    ]
