# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
