# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20170416_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='typical_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='typical_low',
            field=models.FloatField(null=True),
        ),
    ]
