# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20170416_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='rloiid',
            field=models.IntegerField(null=True),
        ),
    ]
