# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20170416_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='station_ref',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
