# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_auto_20170419_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='measure_url',
            field=models.CharField(default='na', max_length=150),
            preserve_default=False,
        ),
    ]
