# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_stations_measure_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='measure_url',
            new_name='measure',
        ),
    ]
