# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_auto_20170423_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='reading_type_id',
            new_name='reading_type',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='stationreadings',
            old_name='station_id',
            new_name='station',
        ),
    ]
